// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlzy9AySYGqVK7YAbatIVxVT263HVYXWE',
    appId: '1:165997945375:web:eafb6ae0ccbe30673fab2a',
    messagingSenderId: '165997945375',
    projectId: 'smartmarket-e2148',
    authDomain: 'smartmarket-e2148.firebaseapp.com',
    storageBucket: 'smartmarket-e2148.firebasestorage.app',
    measurementId: 'G-2WQY2G34KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDToIW7g-C1hVbxqA1-uNfr9Q6uh4quZc',
    appId: '1:165997945375:android:071c279456a195623fab2a',
    messagingSenderId: '165997945375',
    projectId: 'smartmarket-e2148',
    storageBucket: 'smartmarket-e2148.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAg4Yngb4K2-GSRKnXXtoa69_q5v7gho',
    appId: '1:165997945375:ios:c0c8d5e68d1af95f3fab2a',
    messagingSenderId: '165997945375',
    projectId: 'smartmarket-e2148',
    storageBucket: 'smartmarket-e2148.firebasestorage.app',
    iosBundleId: 'com.example.smartmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAg4Yngb4K2-GSRKnXXtoa69_q5v7gho',
    appId: '1:165997945375:ios:c0c8d5e68d1af95f3fab2a',
    messagingSenderId: '165997945375',
    projectId: 'smartmarket-e2148',
    storageBucket: 'smartmarket-e2148.firebasestorage.app',
    iosBundleId: 'com.example.smartmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlzy9AySYGqVK7YAbatIVxVT263HVYXWE',
    appId: '1:165997945375:web:f3cdebbd94589b373fab2a',
    messagingSenderId: '165997945375',
    projectId: 'smartmarket-e2148',
    authDomain: 'smartmarket-e2148.firebaseapp.com',
    storageBucket: 'smartmarket-e2148.firebasestorage.app',
    measurementId: 'G-K9PBMDQX4X',
  );
}
